[tox]
envlist = py, min

[testenv]
deps =
    pytest
    sphinx-design
    sphinxcontrib-httpdomain
    sphinxcontrib-youtube
commands =
    pytest {posargs}

[testenv:min]
basepython = python3.10
deps =
    {[testenv]deps}
    sphinx==7.4.0
